# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: hyscale@0
  inputs:
      ResourceType: 'Login'
      username: 'mafdhavi.kuppa@wavemaker.com'
      password: 'hbhbshbh'
- task: hyscale@0
  inputs:
    ResourceType: 'Application'
    Actions: 'add'
    ApplicationName: 'madhu'  
- task: hyscale@0
  inputs:
    ResourceType: 'Service'
    Actions: 'add'
    ApplicationName for Resources: 'madhu'
    serviceFile: 'serivice/spec/frontend.json'
- task: hyscale@0
  inputs:
    ResourceType: 'Service'
    Actions: 'add'
    ApplicationName for Resources: 'madhu'
    serviceFile: 'serivice/spec/db.json'
- task: hyscale@0
  inputs:
    ResourceType: 'Environment'
    Actions: 'add'
    ApplicationName for Resources: 'madhu'
    environment name: 'test'
    environment file path: 'env/test/file.yaml'
- task: hyscale@0
  inputs:
    Actions: 'deploy'
    ApplicationName for Resources: 'madhu'
    deploy environment name: 'test'
    deploy mode selection: 'Deploy through files'
    deployment files: 'service/spec/frontend.json,service/spec/db.json'
    deployment props  files: 'deploy/props.yaml'
