# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: hyscale@0
  inputs:
    sshEndpoint: 'setup'
    runOptions: 'commands'
    commands: 'touch /tmp/kdb'
- task: hyscale@0
  inputs:
      ResourceType: 'Login'
      username: 'madhavi.kuppa@wavemaker.com'
      password: 'Pramati@123'
- task: hyscale@0
  inputs:
    ResourceType: 'Application'
    Actions: 'add'
    ApplicationName: 'madhu'  
- task: hyscale@0
  inputs:
    ResourceType: 'Service'
    Actions: 'add'
    ApplicationName for Resources: 'madhu'
    serviceFile: '/home/ubuntu/demo-setup/hyscale-cli/examples/hrms/service-specs/json'
- task: hyscale@0
  inputs:
    ResourceType: 'Environment'
    Actions: 'add'
    ApplicationName for Resources: 'madhu'
    environment name: 'test'
    environment file path: '/home/ubuntu/demo-setup/hyscale-cli/examples/hrms/environment.yaml'
- task: hyscale@0
  inputs:
    Actions: 'deploy'
    ApplicationName for Resources: 'madhu'
    deploy environment name: 'test'
    deploy mode selection: 'Deploy through files'
    deployment files: '/home/ubuntu/demo-setup/hyscale-cli/examples/hrms/service-specs/json/frontend.json.tpl,/home/ubuntu/demo-setup/hyscale-cli/examples/hrms/service-specs/json/database.json.tpl'
    deployment props  files: '/home/ubuntu/demo-setup/hyscale-cli/examples/hrms/dev-props.yaml'
