# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: hyscale@0
  inputs:
    ResourceType: 'Login'
    username and password: 'user pass'
- task: hyscale@0
  inputs:
    ResourceType: 'Application'
    Actions: 'add'
    ApplicationName: 'inputTest'
- task: hyscale@0
  inputs:
    ResourceType: 'Service'
    Actions: 'add'
    ApplicationName for Resources: 'inputTest'
    serviceFile: 'hrms/service/specs.json'
- task: hyscale@0
  inputs:
    ResourceType: 'Environment'
    Actions: 'add'
    ApplicationName for Resources: 'inputTest'
    environment name: 'testenv'
    environment file path: 'hrms/env/file.yaml'
- task: hyscale@0
  inputs:
    Actions: 'deploy'
    ApplicationName for Resources: 'inputTest'
    deploy environment name: 'testenv'
    deploy mode selection: 'Deploy through files'
    deployment files: 'frontend/file.json,backend/file.json'
    deployment props  files: 'props/deploy.yaml'
